[package]
name = "complex"
version = "0.1.0"
authors = ["Michael Hazoglou <michaelhazoglou@gmail.com>"]
edition = "2018"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"